import React, { useState } from 'react'

const ERROR_IMG_SRC =
  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODgiIGhlaWdodD0iODgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgc3Ryb2tlPSIjMDAwIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBvcGFjaXR5PSIuMyIgZmlsbD0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIzLjciPjxyZWN0IHg9IjE2IiB5PSIxNiIgd2lkdGg9IjU2IiBoZWlnaHQ9IjU2IiByeD0iNiIvPjxwYXRoIGQ9Im0xNiA1OCAxNi0xOCAzMiAzMiIvPjxjaXJjbGUgY3g9IjUzIiBjeT0iMzUiIHI9IjciLz48L3N2Zz4KCg=='

// PREVIOUSLY: auto-generated a WebP sibling path for any root-rooted JPG/PNG
// and emitted it as a <picture><source>. That assumed every public/*.jpg|png
// in the bundle had a matching .webp file. It did NOT — only the Smacks JPGs
// had webp pairs (generated by scripts/generate-smack-share-pages.mjs). For
// every other image (org logos, card uploads like be-pretti-good-beanie.jpg)
// the webp <source> 404'd and Chrome silently failed to fall back to the
// <img>, rendering the gray placeholder icon. Symptom: dozens of cards
// looked imageless even though the .jpg was right there on disk + S3.
//
// Disabled until we either (a) build-time generate webp siblings for every
// public/* JPG/PNG via sharp in `prebuild`, or (b) opt-in callers explicitly.
function webpSibling(_src: unknown): string | null {
  return null
}

export function ImageWithFallback(props: React.ImgHTMLAttributes<HTMLImageElement>) {
  const [didError, setDidError] = useState(false)

  const handleError = () => {
    setDidError(true)
  }

  const { src, alt, style, className, ...rest } = props

  if (didError) {
    return (
      <div
        className={`inline-block bg-gray-100 text-center align-middle ${className ?? ''}`}
        style={style}
      >
        <div className="flex items-center justify-center w-full h-full">
          <img src={ERROR_IMG_SRC} alt="Error loading image" {...rest} data-original-url={src as string | undefined} />
        </div>
      </div>
    )
  }

  const webp = webpSibling(src)
  if (webp) {
    return (
      <picture>
        <source srcSet={webp} type="image/webp" />
        <img
          src={src as string}
          alt={alt}
          className={className}
          style={style}
          loading="lazy"
          decoding="async"
          {...rest}
          onError={handleError}
        />
      </picture>
    )
  }

  return (
    <img
      src={src as string | undefined}
      alt={alt}
      className={className}
      style={style}
      loading="lazy"
      decoding="async"
      {...rest}
      onError={handleError}
    />
  )
}
