#!/usr/bin/env python3
"""Regenerate index_merged.ts = index.ts with kv_store.ts inlined.

Run from the repo root:
    python3 supabase/functions/make-server-9eb1ae04/_build_merged.py

The Supabase dashboard's Edge Functions code editor can't follow relative
imports, so `import * as kv from "./kv_store.ts"` breaks when you paste
index.ts into the dashboard. This script produces index_merged.ts — a single
self-contained file that deploys cleanly via paste.

If you set up the Supabase CLI (`supabase functions deploy`), it handles
relative imports correctly and you don't need index_merged.ts at all.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
INDEX = HERE / "index.ts"
KV = HERE / "kv_store.ts"
OUT = HERE / "index_merged.ts"

idx = INDEX.read_text()
kv = KV.read_text()

# Pull the body of kv_store.ts (skipping its preamble + the createClient import,
# which we'll re-emit in the namespace below).
m = re.search(
    r"^// Set stores a key-value pair.*?^export const getByPrefix.*?^};",
    kv,
    re.MULTILINE | re.DOTALL,
)
if not m:
    sys.exit("ERROR: couldn't locate kv_store.ts body (markers changed?)")

# Rename `export const X` → `const _kv_X` so they're file-local, then expose
# them through a `kv` namespace object that matches the import shape used in
# index.ts (`import * as kv from "./kv_store.ts"; kv.set(...)`).
kv_local = re.sub(r"^export const (\w+)", r"const _kv_\1", m.group(0), flags=re.MULTILINE)
kv_local = kv_local.replace("client()", "kvClient()")

namespace = f"""
// ─── KV namespace (inlined from kv_store.ts) ─────────────────────────────────
const kvClient = () => createClient(
  Deno.env.get("SUPABASE_URL")!,
  serviceRoleKey(),
);

{kv_local}

const kv = {{
  set: _kv_set, get: _kv_get, del: _kv_del,
  mset: _kv_mset, mget: _kv_mget, mdel: _kv_mdel,
  getByPrefix: _kv_getByPrefix,
}};
"""

# Drop the relative import from index.ts; we replace it with the inlined ns.
idx2 = re.sub(r'import \* as kv from "\./kv_store\.ts";\s*\n', "", idx)

# Inject the namespace right after the run of `import` statements at the top.
import_block = re.search(r"((?:^import .*\n)+)", idx2, re.MULTILINE)
if not import_block:
    sys.exit("ERROR: no leading import block found in index.ts")

merged = idx2[: import_block.end()] + namespace + idx2[import_block.end() :]

header = (
    "// AUTOGENERATED — do not edit by hand.\n"
    "// This is `index.ts` with `kv_store.ts` inlined into a single file, suitable\n"
    "// for pasting into the Supabase dashboard's Edge Functions code editor (which\n"
    "// can't follow the relative `./kv_store.ts` import). Regenerate after editing\n"
    "// index.ts by running:\n"
    "//\n"
    "//   python3 supabase/functions/make-server-9eb1ae04/_build_merged.py\n"
    "//\n"
)
# Strip any prior header so we don't accumulate them.
merged = re.sub(r"^// AUTOGENERATED.*?(?=^import )", "", merged, count=1, flags=re.MULTILINE | re.DOTALL)
merged = header + merged

OUT.write_text(merged)
print(f"Wrote {OUT.relative_to(HERE.parents[2])}")
print(f"  index.ts:        {len(idx.splitlines())} lines")
print(f"  index_merged.ts: {len(merged.splitlines())} lines")
